syntax enable                 " use syntax highlighting
filetype plugin indent on     " use filetype-specific indent options
let g:netrw_dirhistmax = 0    " don't save .vim directory changes in .netrwhist

set autoindent                " copy indent from current line when starting a new line
set nocompatible              " use Vim defaults, not vi
set clipboard=unnamedplus     " use + flag with y and d (copy and paste using system keyboard)
set nospell spelllang=en_au   " don't highlight mispelled words by default
set relativenumber            " show relative line numbers
set number                    " show absolute line number of current line
set wildmenu                  " visual autocomplete for command menu
set showmatch                 " highlight matching [{()}]
set incsearch                 " search as characters are entered
set ignorecase                " ignore case in search patterns
set encoding=utf-8            " set how vim represents characters internally
set expandtab                 " tabs are spaces
set laststatus=2              " makes status lines display
set tabstop=2                 " number of visual spaces per TAB
set softtabstop=2             " number of spaces in tab when editing
set shiftwidth=2              " number of spaces to move when ussing >> << and ==
set history=3000              " keep a lot command line history
set undolevels=1000           " set maximum amount of undos
set autoread                  " watch for file changes
set noshowmode                " don't show the mode, we have powerline
set writebackup               " create a backup of open files
set foldmethod=indent         " fold code based on indent level
set foldlevelstart=20         " open files with all folds open
set ssop-=options             " do not store global and local values in a session file
set hlsearch                  " highlight results after a search

set backupdir=~/tmp/swapfiles//,/tmp//
set directory=~/tmp/swapfiles//,/tmp//

nmap \p :set paste!<CR>       " toggle paste mode
nmap \l :setlocal number!<CR> " toggle line numbers
nmap \h :nohlsearch<CR>       " remove highlights
nmap <C-n> :bnext<CR>         " go to next buffer
nmap <C-p> :bprev<CR>         " go to previous buffer

" move multiple lines with ctrl-movement
nnoremap <C-j> 5j
nnoremap <C-k> 5k
xnoremap <C-j> 5j
xnoremap <C-k> 5k

" increase indent of selection with tab
vnoremap <Tab> >gv
vnoremap <S-Tab> <LT>gv

" move selection with J and K
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

colorscheme molokai
